/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Progressbar extends java.applet.Applet {

    /**
     * Initializes the applet Progressbar
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        progressbar3 = new progressbar.Progressbar();
        progressbar4 = new progressbar.Progressbar();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Which Language Do You Like The Most?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 20));

        jButton1.setText("PHP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 40));

        jButton2.setText("Java");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 40));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 40));
        add(progressbar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 30, 40));
        add(progressbar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 30, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    progressbar3.increment();
     int value1 = (int) progressbar3.getValue();
        int value2 = (int) progressbar4.getValue();
        int value3 = value1+value2;
   
        if (value2 == 0){
            jProgressBar1.setValue(value1);
        }
        else {
            jProgressBar1.setValue(value2);
        }
        jProgressBar1.setMaximum(value3);
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     progressbar4.increment();
         int value1 = (int) progressbar3.getValue();
        int value2 = (int) progressbar4.getValue();
        int value3 = value1+value2;
          if (value1 == 0){
            jProgressBar1.setValue(value2);
        }
        else {
            jProgressBar1.setValue(value1);
        }
        jProgressBar1.setMaximum(value3);
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private progressbar.Progressbar progressbar3;
    private progressbar.Progressbar progressbar4;
    // End of variables declaration//GEN-END:variables
}
